/** Korean manhwa and webtoon SFX. Matched with hangul elongation and repeats in `sfx.ts`. */

export const KOREAN_SFX_TEXT = `
# Breath, voice
하 = sigh / ha
하아 = sigh
후 = sigh / exhale / blow
후우 = sigh / exhale
휴 = whew / sigh of relief
헉 = gasp
헐 = gasp / what
헛 = gasp / sharp breath
흡 = sharp inhale
흐음 = hmm
흐으 = groan / trailing off
으으 = groan / shiver
끄응 = groan / strain
크응 = groan / strain
푸하 = exhale / gasp for air
하암 = yawn
콜록 = cough
콜록콜록 = cough cough
쿨럭 = cough
쿨럭쿨럭 = cough cough
켁 = choke
에취 = achoo
엣취 = achoo
흑 = sob
흑흑 = sob sob
엉엉 = wail / bawl
으앙 = waaah / bawl
으아 = wail
흐윽 = sob
훌쩍 = sniffle
훌쩍훌쩍 = sniffle
응애 = baby's cry
킁 = sniff
킁킁 = sniff sniff

# Laughter
하하 = haha
호호 = hoho / soft laugh
히히 = hehe
헤헤 = hehe / silly laugh
흐흐 = heh / sinister laugh
허허 = hoho / hearty laugh
킥킥 = giggle
킬킬 = snicker
키득 = giggle
키득키득 = giggle
크크 = chuckle
까르르 = bright laugh
깔깔 = laugh loudly
껄껄 = hearty laugh
푸흡 = snort / stifle a laugh
푸핫 = burst out laughing
피식 = smirk / snort
싱긋 = smile
히죽 = grin
히죽히죽 = grin
ㅋㅋ = lol
ㅎㅎ = hehe
ㅠㅠ = sob / tears
ㅜㅜ = sob / tears

# Heart, flush, nerves
두근 = thump / heartbeat
두근두근 = thump thump / pounding heart
콩닥 = ba-dump / heart skip
콩닥콩닥 = heart pounding
쿵 = thud / heart drop
쿵쿵 = thump thump / pounding
벌렁 = heart leap
벌렁벌렁 = heart racing
철렁 = heart sinks
철렁철렁 = sinking dread
울컥 = well up / surge of emotion
뭉클 = heart-tug / touched
찡 = pang / sting of tears
시큰 = sting
글썽 = eyes well up
글썽글썽 = teary
화끈 = flush
화끈화끈 = burning flush
발그레 = blush
후끈 = heat / warm flush
후끈후끈 = flushed with heat
따끈 = warm
따끈따끈 = warm
오싹 = shiver / creepy chill
으슬으슬 = chilly shiver
부들부들 = trembling
바들바들 = shivering
덜덜 = shiver / chatter
오들오들 = shivering
파르르 = tremble / flutter
사르르 = melt / soften / drift off
조마조마 = on edge / anxious
안절부절 = restless
허둥지둥 = flustered
우왕좌왕 = milling in panic
갈팡질팡 = flustered
머쓱 = awkward / sheepish
쭈뼛 = fidget
쭈뼛쭈뼛 = fidgeting
머뭇 = hesitate
머뭇머뭇 = hesitating
꼬물꼬물 = squirm / fidget
꼼지락 = fidget
꼼지락꼼지락 = fidgeting
설레설레 = flutter / excited
까딱 = twitch / flick
까딱까딱 = twitching
깜짝 = startled
화들짝 = startled jump
흠칫 = flinch
움찔 = flinch / twitch
움찔움찔 = twitch
벌떡 = spring up
풀썩 = slump / collapse
털썩 = plop / collapse
픽 = slump
푹 = sink / plop
꾸벅 = nod off
꾸벅꾸벅 = nodding off

# Face, gaze, light
힐끔 = glance
힐끗 = glance
힐끔힐끔 = glancing
힐끗힐끗 = glancing
흘끗 = glance
슬쩍 = sneak / casually
슬쩍슬쩍 = sneaking glances
깜빡 = blink
깜빡깜빡 = blinking
깜박 = blink
깜박깜박 = blinking
껌벅껌벅 = slow blink
말똥말똥 = wide-eyed
초롱초롱 = bright-eyed
반짝 = sparkle
반짝반짝 = sparkling
번쩍 = flash
번쩍번쩍 = flashing
번뜩 = gleam
찌릿 = tingle / jolt
찌릿찌릿 = tingling
부릅 = eyes snap wide
지끈 = splitting pain
지끈지끈 = splitting headache
욱신 = throb
욱신욱신 = throbbing

# Gesture, touch, steps
끄덕 = nod
끄덕끄덕 = nodding
꼬덕꼬덕 = nodding
도리도리 = shake head
절레절레 = shake head
슥 = slide
스윽 = smooth slide
스르륵 = slide / slip down
스르르 = drift / slide softly
쓰담쓰담 = pat / stroke
토닥토닥 = pat pat
꽉 = squeeze
꼬옥 = squeeze / hug tightly
덥석 = grab
훅 = whoosh / sudden grab
확 = sudden motion
탁 = tap
툭 = tap / flick
툭툭 = tap tap
콕 = poke
콕콕 = poke poke
쿡 = poke
쪽 = kiss
뽀뽀 = kiss
할짝 = lick
할짝할짝 = licking
살살 = gently
살금살금 = tiptoe / stealthy
사뿐사뿐 = light steps
성큼 = stride
성큼성큼 = striding
폴짝 = hop
폴짝폴짝 = hopping
통통 = bounce
으쓱 = shrug
쓱 = swipe
쓱쓱 = swipe / rub
벅벅 = scrub
싹싹 = wipe
쭉 = stretch
바짝 = tightly / right up close
바싹 = tightly
슬금슬금 = sneaking
슬그머니 = stealthily
기웃 = peek
기웃기웃 = peeking
빼꼼 = peek
빼꼼빼꼼 = peeking
후다닥 = scramble
아장아장 = toddle
뒤뚱뒤뚱 = waddle
엉금엉금 = crawl
뚜벅뚜벅 = footsteps
저벅저벅 = heavy footsteps
터벅터벅 = trudging
총총 = light quick steps
종종 = trot
다다다 = rapid footsteps
타다닥 = scurrying
다그닥 = clatter of steps
사박사박 = soft footsteps

# Impact, break, combat
딱 = smack / snap
짝 = slap
짝짝 = clap
찰싹 = slap / splash
철썩 = splash / smack
퍽 = wham
퍽퍽 = wham wham
퍼억 = wham
팍 = smack
탕 = bang
탕탕 = bang bang
쾅 = bam / slam
쾅쾅 = bam bam
펑 = boom / pop
팡 = pop / burst
빵 = bang
뻥 = boom
콰광 = boom
콰당 = crash
콰앙 = boom
콰직 = smash
콰르르 = rumble / crumble
우르르 = rumble / rush
우르릉 = thunder / rumble
와장창 = crash / smash
와르르 = tumble down / collapse
쿠당탕탕 = crashing
우당탕 = crash / clatter
우당탕탕 = crashing about
쿵쾅 = stomp / bang
쿵쾅쿵쾅 = stomping
우지끈 = crack / snap
우지직 = rip / crack
우드득 = crunch / crack
으드득 = crunch / grind
으득 = grind
파직 = crack / zap
파지직 = electric crackle
지직 = static / rip
찌익 = rip
지지직 = crackling
챙 = clang
챙챙 = clash
카앙 = clang
까앙 = clang
채앵 = blade ring
스릉 = shing / blade draw
쉬익 = slash / hiss
철컹 = clank
철컥 = clack / latch
철푸덕 = splat
철커덕 = latch clunk
퍼엉 = boom

# Scream, aura, motion
악 = scream
꺄 = shriek
꺄악 = shriek
으악 = scream
크악 = scream
아악 = scream
크아 = scream
콰아 = crash / whoosh
화아 = flare
화악 = flare / whoosh
파아 = flare / aura
파앗 = flare / burst
휙 = swish
획 = swish / quick turn
휘익 = whoosh
슈웅 = whoosh
슈욱 = whoosh
휘잉 = wind / whoosh
휘이 = wind
쌩 = zoom
쌩쌩 = whoosh / speeding
부웅 = vroom
부릉 = vroom
붕 = zoom
윙 = whirr
위잉 = whirr
웅 = rumble / hum
우웅 = hum / power
우우웅 = ominous hum
빙글빙글 = spinning
뱅글뱅글 = spinning
데굴데굴 = roll
또르르 = roll / tears rolling
휘리릭 = whirl
꿈틀 = wriggle
꿈틀꿈틀 = wriggling
스멀스멀 = creeping

# Doors, objects, alerts
끼익 = creak
삐걱 = creak
삐걱삐걱 = creaking
드르륵 = slide / rumble
드르르 = rumble
달그락 = clatter
달그락달그락 = clattering
덜그럭 = rattle
덜컹 = jolt / rattle
덜컹덜컹 = rattling
딸깍 = click
찰칵 = click / shutter
똑 = tick / drip
똑딱 = tick-tock
째깍째깍 = tick-tock
딩동 = ding-dong
땡 = clang / buzzer
딸랑딸랑 = jingling
짤랑짤랑 = jingling
따르릉 = ring ring
띠링 = ding
삐 = beep
삐삐 = beep beep
윙윙 = buzz / vibrate
타닥타닥 = tap / typing
털털 = rattle
푸드득 = flutter / takeoff
팔랑팔랑 = flutter
펄럭 = flap
펄럭펄럭 = flapping
살랑살랑 = rustle / breeze
흔들흔들 = sway
출렁 = slosh
출렁출렁 = sloshing
일렁일렁 = rippling

# Water, fire, weather, texture
주르륵 = trickle / stream down
주룩주룩 = pouring
후두둑 = patter
보슬보슬 = drizzle
부슬부슬 = drizzle
추적추적 = steady rain
첨벙 = splash
풍덩 = plunge
졸졸 = trickle
콸콸 = gushing
철철 = overflowing
뚝뚝 = drip drip
보글보글 = bubble / simmer
부글부글 = boil / seethe
지글지글 = sizzle
치익 = hiss / sizzle
화르륵 = flare up
화르르 = blaze
활활 = blazing
이글이글 = blazing
모락모락 = wisp / steam
솔솔 = waft / breeze
우수수 = shower down
바스락 = rustle
바스락바스락 = rustling
부스럭 = rustle
부스럭부스럭 = rustling
사각사각 = scratch / soft rustle
말랑말랑 = squishy
폭신폭신 = soft / fluffy
보들보들 = soft
끈적끈적 = sticky
미끌미끌 = slippery
까슬까슬 = rough
매끈매끈 = smooth
촉촉 = moist
축축 = damp
뽀송뽀송 = soft and dry
송글송글 = beads of sweat
포슬포슬 = soft fall

# Eat, drink, sleep
냠냠 = nom nom
우적우적 = munch
아그작 = crunch
아삭아삭 = crispy crunch
바삭바삭 = crispy
와작 = crunch
홀짝홀짝 = sipping
꿀꺽 = gulp
꿀꺽꿀꺽 = gulp gulp
꼴깍 = gulp
벌컥 = burst
벌컥벌컥 = gulping
후루룩 = slurp
쩝쩝 = smacking lips
꼬르륵 = stomach growl
꾸르륵 = stomach growl
꺼억 = burp
쿨쿨 = snore / sleep
드르렁 = snore
새근새근 = sleeping peacefully

# Creatures
멍멍 = woof
왈왈 = arf
컹컹 = bark
야옹 = meow
냥 = meow
꿀꿀 = oink
음메 = moo
매애 = baa
꼬끼오 = cock-a-doodle-doo
꼬꼬댁 = cluck
꽥꽥 = quack
짹짹 = chirp
구구 = coo
까악 = caw
찍찍 = squeak
어흥 = roar
크르릉 = growl
으르렁 = growl
히힝 = neigh
삐약 = cheep
개굴개굴 = ribbit

# Crowd
소곤소곤 = whisper
소근소근 = whisper
속닥속닥 = whisper
웅성웅성 = murmur
와글와글 = bustle
시끌시끌 = clamor
시끌벅적 = ruckus
재잘재잘 = chatter
쉿 = shh
`;
